pipeline{
    agent{
        docker{
            image 'maven:3.6.3-jdk-11'
            args '-v/root/.m2:/root/.m2'
        }
    }
      
        stages{
            stage('Git-Checkout')
            {
              steps{
                    sh 'rm -rf Java'
                     git 'https://github.com/sreelakshmi665/Java.git'
                }
            }
    
             stage('Validate')
        {
            steps{
              sh 'mvn -f Java  clean validate'
            }
        }
        stage('Compile')
        {
            steps{
               sh 'mvn -f Java compile'
            }
        }
            stage('sonar analysis'){
            steps{
                 script{      
                withSonarQubeEnv('sonar-server'){
                    
                        sh 'mvn -f Java sonar:sonar'
                    
                    }
                }
            }

        }
             stage("Quality gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
            
        stage('Test')
        {
            steps{
                sh 'mvn -f Java test'
            }
        }
        stage('Package')
        {
            steps{
               sh 'mvn -f Java package'
            }
        }
        stage('Verify')
        {
            steps{
               sh 'mvn -f Java verify'
            }
        }
        stage('Install')
        {
            steps{
                sh 'mvn -f Java install'
            }
        }
             stage('Artifactory')
    {
      steps{
           script{
                        
        archiveArtifacts artifacts:'Java/target/*.jar',followSymlinks:false
           }
      }
    }
        
    stage('Deploy-To-Artifactory')
    {
      steps{
           script{
                       
        rtUpload(
          serverId:'artifactory-server',
          spec: '''{
          "files": [
            {
              "pattern": "Java/target/*.jar",
              "target": "art-doc-dev-loc"
            }
         ]
    }''',
          
)
  }
}   
    } 
            
            
           
        }
     post {  
         always {  
             echo 'This will always run'  
         }  
         success {  
             echo 'This will run only if successful'
              mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> Success!! <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sreelakshmilucky14@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sreelakshmilucky14@gmail.com"; 
             sshagent(['88937939-1f6c-4ce3-abf3-4596f847bc3b']){
                    bat 'scp -r C:/Users/vscr9/.m2/repository/codingChallenge1-0.0.1-SNAPSHOT.jar ubuntu@13.233.49.82:/home/ubuntu/artifacts'     
        }
         }  
         failure {  
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER}<br> Failure!! <br> <br>Build Failed Stage: ${FAILED_STAGE} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sreelakshmilucky14@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sreelakshmilucky14@gmail.com";  
         }  
         unstable {  
             echo 'This will run only if the run was marked as unstable'  
         }  
         changed {  
             echo 'This will run only if the state of the Pipeline haschanged'  
             echo 'For example, if the Pipeline was previously failing but is now successful'  
         }  
     }    
}
