pipeline{
    agent any
    tools{
    maven 'Maven'
    jdk 'jdk'
    }
        
        stages{
            stage('Git-Checkout')
            {
              steps{
                     git 'https://github.com/sreelakshmi665/Java.git'
                }
            }
             stage('Clean')
        {
            steps{
              bat 'mvn -f Java clean'
            }
        }
             stage('Validate')
        {
            steps{
              bat 'mvn -f Java validate'
            }
        }
        stage('Compile')
        {
            steps{
               bat 'mvn -f Java compile'
            }
        }
        stage('Test')
        {
            steps{
                bat 'mvn -f Java test'
            }
        }
        stage('Package')
        {
            steps{
               bat 'mvn -f Java package'
            }
        }
        stage('Verify')
        {
            steps{
               bat 'mvn -f Java verify'
            }
        }
        stage('Install')
        {
            steps{
                bat 'mvn -f Java install'
            }
        }
            
            
           
        }
}
