pipeline{
    agent{
        docker{
            image 'maven:3.6.3-jdk-11'
            args '-v/root/.m2:/root/.m2'
        }
    }
      
        stages{
            stage('Git-Checkout')
            {
              steps{
                    sh 'rm -rf Java'
                     git 'https://github.com/sreelakshmi665/Java.git'
                }
            }
    
             stage('Validate')
        {
            steps{
              sh 'mvn -f Java  clean validate'
            }
        }
        stage('Compile')
        {
            steps{
               sh 'mvn -f Java compile'
            }
        }
            stage('sonar analysis'){
            steps{
                 script{      
                withSonarQubeEnv('sonar-server'){
                    
                        sh 'mvn -f Java sonar:sonar'
                    
                    }
                }
            }

        }
            
        stage('Test')
        {
            steps{
                sh 'mvn -f Java test'
            }
        }
        stage('Package')
        {
            steps{
               sh 'mvn -f Java package'
            }
        }
        stage('Verify')
        {
            steps{
               sh 'mvn -f Java verify'
            }
        }
        stage('Install')
        {
            steps{
                sh 'mvn -f Java install'
            }
        }
            
            
           
        }
}
